"""Add run_model_usage table

Revision ID: 005_run_model_usage
Revises: dde00df6f577
Create Date: 2025-08-28 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005_run_model_usage'
down_revision: Union[str, None] = 'dde00df6f577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_model_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('node_key', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_run_model_usage_provider', 'run_model_usage', ['provider', 'model_name'], unique=False)
    op.create_index('ix_run_model_usage_run_id', 'run_model_usage', ['run_id'], unique=False)
    op.create_index('ix_run_model_usage_run_node', 'run_model_usage', ['run_id', 'node_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_model_usage_run_node', table_name='run_model_usage')
    op.drop_index('ix_run_model_usage_run_id', table_name='run_model_usage')
    op.drop_index('ix_run_model_usage_provider', table_name='run_model_usage')
    op.drop_table('run_model_usage')
    # ### end Alembic commands ###