"""Add daily_run_stats table

Revision ID: 006_daily_run_stats
Revises: 005_run_model_usage
Create Date: 2025-08-28 12:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006_daily_run_stats'
down_revision: Union[str, None] = '005_run_model_usage'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_run_stats',
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('runs_started', sa.Integer(), nullable=False),
    sa.Column('runs_completed', sa.Integer(), nullable=False),
    sa.Column('avg_total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('fallbacks_used', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_run_stats')
    # ### end Alembic commands ###