name: Deploy Backend to Azure App Service

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: cp-app-szbxw7
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt
        # Verify critical dependencies
        python -c "import uvicorn, fastapi, gunicorn; print('Dependencies installed successfully')"

    - name: Create deployment package
      run: |
        # Remove unnecessary files for deployment
        rm -rf .git .github __pycache__ *.pyc .env.example
        ls -la

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

    - name: Deployment Summary
      run: |
        echo "✅ Backend deployment completed successfully!"
        echo "🔗 Application URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        echo "🏥 Health Check: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/healthz"
        echo "📚 API Docs: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/docs"
        echo ""
        echo "Note: Startup command configured separately via Azure CLI"